### ISSUE TITLE
Is there a reason TEXT is not accepted in MySQL?

### ISSUE THREAD

**Issue by Gregam3** [naynecoder/yorm#17]
Is there a reason why `TEXT` is not in the `org.yorm.util.DbType`? Leading to the error `There is no DbType for sqlType:-1`

P.S. I'm very excited by the prospect of a record-based ORM In java

**Comment by naynecoder** [comment]
Good point, indeed there is no reason no to have TEXT. It's been merged as part of release 0.0.5, it will be shortly deployed in Maven Central, thanks for asking!
